sudo: required

language: cpp

services:
  - docker

before_install:
  - docker build -t streetlightd ci/

script:
  - docker run -v `pwd`:/home/root/streetlightd streetlightd bash -c "cd home/root/streetlightd/; ci/build.sh"
  - docker run -v `pwd`:/home/root/streetlightd streetlightd bash -c "cd home/root/streetlightd/; ci/test.sh"
